namespace Simple.Compiler.Syntax;

public enum TokenKind
{
    BadToken,
    EndOfFile,

    Identifier,
    NumberLiteral,
    StringLiteral,
    CharLiteral,
    TrueKeyword,
    FalseKeyword,

    // Keywords
    WhileKeyword,
    ForKeyword,
    BreakKeyword,
    SkipKeyword,
    ReturnKeyword,
    DefaultKeyword,
    FnKeyword,
    SelfKeyword,
    ArtifactKeyword,
    EnumKeyword,
    ModuleKeyword,
    UnionKeyword,

    // Punctuation
    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    OpenBracket,
    CloseBracket,
    Comma,
    Semicolon,
    Dot,

    // Operators
    Colon,
    DoubleColon,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    PlusPlus,
    MinusMinus,
    Ampersand,
    Pipe,
    Caret,
    ShiftLeft,
    ShiftRight,
    EqualsEquals,
    BangEquals,
    Less,
    Greater,
    LessOrEquals,
    GreaterOrEquals,
    AmpersandAmpersand,
    PipePipe,
    Bang,
    Equals,
    PlusEquals,
    MinusEquals,
    StarEquals,
    SlashEquals,
    PercentEquals,
    AmpersandEquals,
    PipeEquals,
    CaretEquals,
    ShiftLeftEquals,
    ShiftRightEquals,
    PipeArrow,
}
