#include "RAST/import_index.h"

#include "RAST/import_paths.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <unordered_set>
#include <system_error>

namespace Simple::Lang::RAST {

namespace {

bool ReadFileText(const std::filesystem::path& path, std::string* out) {
  if (!out) return false;
  std::ifstream in(path, std::ios::binary);
  if (!in) return false;
  *out = std::string((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
  return true;
}

} // namespace

bool ExtractModuleHeaderName(const std::string& text, std::string* out) {
  if (!out) return false;
  size_t start = 0;
  while (start <= text.size()) {
    size_t end = text.find('\n', start);
    if (end == std::string::npos) end = text.size();
    std::string line = text.substr(start, end - start);
    const size_t comment = line.find("//");
    if (comment != std::string::npos) line = line.substr(0, comment);
    const size_t first = line.find_first_not_of(" \t\r");
    if (first == std::string::npos) {
      if (end == text.size()) break;
      start = end + 1;
      continue;
    }
    if (line.compare(first, 7, "package") != 0 ||
        (first + 7 < line.size() && !std::isspace(static_cast<unsigned char>(line[first + 7])))) {
      return false;
    }
    size_t pos = first + 7;
    while (pos < line.size() && std::isspace(static_cast<unsigned char>(line[pos]))) ++pos;
    size_t name_end = pos;
    while (name_end < line.size()) {
      const char c = line[name_end];
      if (!(std::isalnum(static_cast<unsigned char>(c)) || c == '_' || c == '.')) break;
      ++name_end;
    }
    if (name_end == pos) return false;
    *out = line.substr(pos, name_end - pos);
    return true;
  }
  return false;
}

bool BuildSimpleFileIndex(const std::filesystem::path& project_root,
                          ImportPathIndex* out) {
  if (!out) return false;
  out->clear();
  namespace fs = std::filesystem;
  std::error_code ec;
  fs::recursive_directory_iterator it(
      project_root,
      fs::directory_options::skip_permission_denied,
      ec);
  if (ec) return false;
  for (const auto& entry : it) {
    if (!entry.is_regular_file()) continue;
    const fs::path& path = entry.path();
    if (path.extension() != ".simple") continue;
    (*out)[path.filename().string()].push_back(fs::weakly_canonical(path, ec));
    if (ec) {
      ec.clear();
      (*out)[path.filename().string()].push_back(fs::absolute(path));
    }
  }
  return true;
}

bool BuildModuleIndex(const std::filesystem::path& project_root,
                      const ImportPathIndex& file_index,
                      ImportPathIndex* out) {
  if (!out) return false;
  out->clear();
  namespace fs = std::filesystem;
  for (const auto& [_, paths] : file_index) {
    for (const auto& path : paths) {
      std::string text;
      if (!ReadFileText(path, &text)) continue;
      std::string module_name;
      if (ExtractModuleHeaderName(text, &module_name)) {
        (*out)[module_name].push_back(path);
      } else {
        const std::string stem = path.stem().string();
        if (!stem.empty()) {
          (*out)[stem].push_back(path);
          std::string capitalized = stem;
          capitalized[0] = static_cast<char>(std::toupper(static_cast<unsigned char>(capitalized[0])));
          if (capitalized != stem) (*out)[capitalized].push_back(path);
        }
      }
    }
  }
  const fs::path map_path = project_root / "simple.modules";
  std::ifstream map_in(map_path);
  if (map_in) {
    std::string line;
    while (std::getline(map_in, line)) {
      ModuleMapEntry entry;
      if (!ParseModuleMapLine(line, &entry)) continue;
      fs::path path = fs::path(entry.path).is_absolute() ? fs::path(entry.path) : (project_root / entry.path);
      std::error_code ec;
      if (!path.has_extension()) path += ".simple";
      (*out)[entry.name].push_back(fs::weakly_canonical(path, ec));
      if (ec) {
        ec.clear();
        (*out)[entry.name].push_back(fs::absolute(path));
      }
    }
  }
  return true;
}

bool WriteAutoModuleMapIfMissing(const std::filesystem::path& project_root,
                                 const ImportPathIndex& module_index) {
  namespace fs = std::filesystem;
  const fs::path map_path = project_root / "simple.modules";
  if (fs::exists(map_path)) return true;
  std::vector<std::pair<std::string, std::filesystem::path>> entries;
  for (const auto& [name, paths] : module_index) {
    std::vector<std::filesystem::path> unique;
    std::unordered_set<std::string> seen;
    for (const auto& path : paths) {
      if (seen.insert(path.string()).second) unique.push_back(path);
    }
    if (unique.size() != 1) continue;
    entries.push_back({name, unique.front()});
  }
  if (entries.empty()) return true;
  std::sort(entries.begin(), entries.end(), [](const auto& a, const auto& b) {
    return a.first < b.first;
  });
  std::ofstream out(map_path);
  if (!out) return false;
  out << "// Auto-generated by simplevm. Maps module names to .simple files.\n";
  for (const auto& [name, path] : entries) {
    std::error_code ec;
    fs::path rel = fs::relative(path, project_root, ec);
    if (ec || rel.empty()) rel = path;
    out << name << "=\"" << rel.generic_string() << "\"\n";
  }
  return true;
}

bool ResolveProjectRootImportPath(const ImportPathIndex& index,
                                  const std::string& import_path,
                                  std::filesystem::path* out,
                                  std::string* error) {
  if (!out) return false;
  const std::string target = ImportPathWithSimpleExtension(import_path);
  auto it = index.find(target);
  if (it == index.end() || it->second.empty()) {
    if (error) *error = "import not found in project root: " + import_path;
    return false;
  }
  if (it->second.size() > 1) {
    std::vector<std::string> matches;
    matches.reserve(it->second.size());
    for (const auto& path : it->second) matches.push_back(path.string());
    std::sort(matches.begin(), matches.end());
    std::string details;
    const size_t limit = std::min<size_t>(5, matches.size());
    for (size_t i = 0; i < limit; ++i) {
      if (i) details += ", ";
      details += matches[i];
    }
    if (matches.size() > limit) details += ", ...";
    if (error) *error = "ambiguous import path '" + import_path + "' matched: " + details;
    return false;
  }
  *out = it->second.front();
  return true;
}

bool ResolveModuleMapImportPath(const std::filesystem::path& base_dir,
                                const std::string& import_path,
                                std::filesystem::path* out) {
  if (!out) return false;
  namespace fs = std::filesystem;
  std::error_code ec;
  fs::path cursor = fs::weakly_canonical(base_dir, ec);
  if (ec || cursor.empty()) cursor = fs::absolute(base_dir);
  while (!cursor.empty()) {
    const fs::path map_path = cursor / "simple.modules";
    std::ifstream map_in(map_path);
    if (map_in) {
      std::string line;
      while (std::getline(map_in, line)) {
        ModuleMapEntry entry;
        if (!ParseModuleMapLine(line, &entry)) continue;
        if (entry.name != import_path) continue;
        fs::path path = fs::path(entry.path).is_absolute() ? fs::path(entry.path) : (cursor / entry.path);
        if (!path.has_extension()) path += ".simple";
        *out = fs::weakly_canonical(path, ec);
        if (ec) {
          ec.clear();
          *out = fs::absolute(path);
        }
        return true;
      }
    }
    if (!cursor.has_parent_path() || cursor.parent_path() == cursor) break;
    cursor = cursor.parent_path();
  }
  return false;
}

bool ResolveModuleImportPath(const ImportPathIndex& module_index,
                             const std::string& import_path,
                             std::filesystem::path* out,
                             std::string* error) {
  if (!out) return false;
  auto it = module_index.find(import_path);
  if (it == module_index.end() || it->second.empty()) return false;
  std::vector<std::filesystem::path> unique;
  std::unordered_set<std::string> seen;
  for (const auto& path : it->second) {
    const std::string key = path.string();
    if (seen.insert(key).second) unique.push_back(path);
  }
  if (unique.size() > 1) {
    if (error) *error = "ambiguous module import: " + import_path;
    return false;
  }
  *out = unique.front();
  return true;
}

bool ResolveLocalImportPath(const std::filesystem::path& base_dir,
                            const ImportPathIndex& project_index,
                            const ImportPathIndex& module_index,
                            const std::string& import_path,
                            std::filesystem::path* out,
                            std::string* error) {
  if (!out) return false;
  namespace fs = std::filesystem;
  fs::path raw(import_path);
  const bool explicit_relative = IsExplicitRelativeImportPath(import_path);

  if (raw.is_absolute()) {
    if (fs::exists(raw)) {
      *out = fs::weakly_canonical(raw);
      return true;
    }
    if (!raw.has_extension()) {
      fs::path with_ext = raw;
      with_ext += ".simple";
      if (fs::exists(with_ext)) {
        *out = fs::weakly_canonical(with_ext);
        return true;
      }
    }
  } else if (explicit_relative) {
    fs::path candidate = base_dir / raw;
    if (fs::exists(candidate)) {
      *out = fs::weakly_canonical(candidate);
      return true;
    }
    if (!raw.has_extension()) {
      fs::path with_ext = base_dir / (import_path + ".simple");
      if (fs::exists(with_ext)) {
        *out = fs::weakly_canonical(with_ext);
        return true;
      }
    }
    if (error) *error = "import file not found: " + import_path;
    return false;
  } else {
    if (ResolveModuleImportPath(module_index, import_path, out, error)) return true;
    if (ResolveModuleMapImportPath(base_dir, import_path, out)) return true;
    if (ResolveProjectRootImportPath(project_index, import_path, out, error)) return true;
    return false;
  }
  if (error) *error = "import file not found: " + import_path;
  return false;
}

} // namespace Simple::Lang::RAST
